# Generated by Django 4.2.2 on 2023-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0002_col_product_col'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='col',
            options={'ordering': ['cifra'], 'verbose_name': 'COL', 'verbose_name_plural': 'COL'},
        ),
        migrations.AddIndex(
            model_name='col',
            index=models.Index(fields=['cifra'], name='tovar_col_cifra_a1322b_idx'),
        ),
    ]
