# Generated by Django 4.2.2 on 2023-11-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0003_alter_col_options_col_tovar_col_cifra_a1322b_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='col',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='col',
            name='tovar_col_cifra_a1322b_idx',
        ),
    ]
